language: node_js
sudo: false
node_js:
   - "node" # latest
env:
   - BROWSER="phantomjs"
   - BROWSER="chrome"
   - BROWSER="firefox"
   - BROWSER="internet explorer"
   - BROWSER="safari"
notifications:
   irc:
      channels: "chat.freenode.net#laxarjs"
      template: "%{repository_slug} (%{commit}) [%{branch}]: %{message}"
